version: "3"

services:
    rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
        volumes:
            - rabbit-mq-etc:/etc/rabbitmq
            - rabbit-mq-data:/var/lib/rabbitmq/
            - rabbit-mq-logs:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
volumes:
  rabbit-mq-etc:
  rabbit-mq-data:
  rabbit-mq-logs:
